import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

import { FcCollapse } from "react-icons/fc";

import SideNavbar from "@/components/leftSideNavbar/leftSideNavbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Navbar />
        <div className="max-w-screen-xl mx-auto grid grid-cols-4">
          {/* Left Sidebar */}
          <SideNavbar />

          {/* Main Content */}
          <main className="col-span-2 w-full mx-auto p-1 min-h-screen">
            {children}
          </main>

          {/* Right Sidebar */}
          <aside className="md:col-span-1  min-h-screen">
            <div className="">
              <h2 className=" text-[8px] md:text-xs font-bold uppercase p-1 bg-gradient-to-b from-white to-[#E5E5E5] flex justify-between">
                See Also 
                <Image src={'/icon1.png'} width={20} height={10} alt="icon" />
              </h2>
              <ul className=" text-[8px] md:text-xs bg-[#EDF8FC] md:p-2 border-t border-blue-200">
                <li>
                  <a href="#" className="flex gap-1  text-[8px] md:text-xs">
                    <FcCollapse className="rotate-90 my-auto" /> SMS user guides
                    (Open in new window)
                  </a>
                </li>
                <li>
                  <a href="#" className="flex gap-1  text-[8px] md:text-xs">
                    <FcCollapse className="rotate-90 my-auto" /> Information for
                    sponsors (Open in new window)
                  </a>
                </li>
                <li>
                  <a href="#" className="flex gap-1  text-[8px] md:text-xs">
                    <FcCollapse className="rotate-90 my-auto" /> Accessibility
                    Statement (Open in new window)
                  </a>
                </li>
                <li>
                  <a href="#" className="flex gap-1  text-[8px] md:text-xs">
                    <FcCollapse className="rotate-90 my-auto" /> Cookie
                    Statement (Open in new window)
                  </a>
                </li>
              </ul>
            </div>
          </aside>
        </div>
      </body>
    </html>
  );
}
